require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'bin/*'
    - 'config/spring.rb'
    - 'db/migrate/2018*'
    - 'db/migrate/201904*'

Layout/ClassStructure:
  Enabled: true
  Exclude:
  Categories:
    module_inclusion:
      - include
      - prepend
      - extend
    association:
      - has_many
      - has_one
      - belongs_to
      - has_and_belongs_to_many
    validations:
      - validate
      - validates_inclusion_of
      - validates_presence_of
    callbacks:
      - before_initialize
      - before_validation
      - before_save
      - before_create
      - before_update
      - before_destroy
      - after_save
      - after_create
      - after_validation
      - after_initialize
      - after_update
      - after_destroy
    enums:
      - enum
    scopes:
      - scope
  ExpectedOrder:
    - association
    - module_inclusion
    - validations
    - constants
    - enums
    - callbacks
    - scopes
    - public_class_methods
    - initializer
    - public_methods
    - protected_methods
    - private_methods

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Metrics:
  Enabled: true

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - 'test/**/*.rb'
  ExcludedMethods: ['included', 'namespace']

Metrics/ClassLength:
  Exclude:
    - 'Rakefile'
    - 'spec/**/*.rb'
    - 'test/**/*.rb'

Metrics/LineLength:
  Enabled: true
  Max: 120
  AllowHeredoc: true
  AllowURI: true
  URISchemes: http, https

Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 15

Naming/MemoizedInstanceVariableName:
  Enabled: false

Rails/Date:
  Enabled: true
  EnforcedStyle: flexible

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/Output:
  Exclude:
    - 'lib/db/postgres_dump_and_restore.rb'

Rails/RefuteMethods:
  Enabled: true

Rails/TimeZone:
  Enabled: true
  EnforcedStyle: flexible

Style/BlockComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: always
  Enabled: true

Style/GuardClause:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

# Technically this performs better, and I got no problem with it.
Style/ParallelAssignment:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/RedundantSelf:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrailingUnderscoreVariable:
  Enabled: false

Style/WhenThen:
  Enabled: true

Style/WordArray:
  Enabled: false
